name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout submodules
        run: git submodule update --init --recursive --depth 1 --jobs 8

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential pkg-config

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: |
            target/*/build/cricket-sys-*/out

      - name: Build
        run: cargo build --workspace --verbose

      - name: Build tests
        run: cargo test --workspace --verbose --no-run

      - name: Test
        run: cargo test --workspace --verbose
